version: '3.9'

services:
  php:
    build:
      context: .
      args:
        php_version: 192.168.101.160:5000/php-oracle
    container_name: itinerario
    ports:
      - "8013:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
